name: maven build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Log in to the ghcr.io container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, deploy and push container image with Maven
        run: ./mvnw --batch-mode --update-snapshots -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}